export const KICKSTARTER_REFRESH_FETCH_LIMIT = 50;
export const KICKSTARTER_PAGE_POOL_LIMIT = 50;
export const KICKSTARTER_RECENT_TARGET = 10;
export const KICKSTARTER_PRE_ENRICH_POOL_LIMIT = 80;
export const KICKSTARTER_DEFAULT_WINDOW_DAYS = 7;
export const KICKSTARTER_MAX_VISIBLE_AGE_DAYS = 90;
export const KICKSTARTER_MIN_PLEDGED_USD = 10_000;
